config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcome#index'
  get 'welcome/yourroute', to: 'welcome#yourroute'
  post 'welcome/index', to: 'welcome#post'
  get 'welcome/comments', to: 'welcome#comments'
  resources :user_routes, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/route.rb
class Route < ApplicationRecord
  require 'open-uri'
  require 'nokogiri'

  has_many :user_routes
  has_many :users, through: :user_routes

  def self.build_route(id)
    route = Route.where(route_id: id).first
    if route.rating
      route
    else
      id = route.route_id
      response = route.call_mp(id)
      route.set_attributes(response)
      comments = route.scrape_mp(id)
      route.set_comments(comments)
      route
    end
  end

  def call_mp(id)
    response = HTTParty.get("https://www.mountainproject.com/data/get-routes?routeIds=#{id}&key=#{Rails.application.credentials.mountain_secret}")
    response.parsed_response
  end

  def set_attributes(response)
    response = response["routes"][0]
   stars = response["stars"]
   rating = response["rating"]
   route_image = response["imgMedium"]
   pitch = response["pitches"]
   lat = response["latitude"]
   lng = response["longitude"]

   self.update(
     stars: stars,
     rating: rating,
     image: route_image,
     pitch: pitch,
     lat: lat,
     lng: lng
   )
  end

  def scrape_mp(id)
    doc = Nokogiri::HTML(open("https://www.mountainproject.com/route/#{id}"))
    doc.css('.comment-body')
  end

  def set_comments(comments)
    if comments.count > 1
      first = comments.first.text.split(" \n")[0].strip
      last = comments.last.text.split(" \n")[0].strip
    elsif comments.count == 1
      first = "This route currently only has one comment"
      last = comments.last.text.split(" \n")[0].strip
    else
      first = "Sorry, no comments for this route"
      last = "Sorry, no comments for this route"
    end
    self.update(
      old_comment: first,
      new_comment: last
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_routes
  has_many :routes, through: :user_routes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 def route_already_added?(route_id)
   route = Route.where(route_id: route_id).first
   return false unless route
   user_routes.where(route_id: route.id).exists?
 end

 def under_route_limit?
   (user_routes.count < 10)
 end

 def can_add_route?(route_id)
   under_route_limit? && !route_already_added?(route_id)
 end
end

app/models/user_route.rb
class UserRoute < ApplicationRecord
  belongs_to :user
  belongs_to :route

end 

app/models/weather.rb
class Weather
  include HTTParty #Seems to work without this, consider removing?
  
  attr_reader :temp, :humidity, :wind, :description
  def initialize(lat, lng)
    call_weather_api(lat, lng)
  end

  def call_weather_api(lat, lng)
    response = HTTParty.get("https://api.openweathermap.org/data/2.5/weather?lat=#{lat}&lon=#{lng}&units=imperial&APPID=#{Rails.application.credentials.weather_secret}")
    parsed_response = response.parsed_response
    set_attributes(parsed_response)
  end

  def set_attributes(parsed_response)
    @temp = parsed_response["main"]["temp"]
    @humidity = parsed_response["main"]["humidity"]
    @wind = parsed_response["wind"]["speed"]
    @description = parsed_response["weather"][0]["description"]
  end
end



=begin
weather = HTTParty.get("https://api.openweathermap.org/data/2.5/weather?lat=#{lat}&lon=#{lng}&units=imperial&APPID=#{Rails.application.credentials.weather_secret}")
@temp = weather.parsed_response["main"]["temp"]
@humidity = weather.parsed_response["main"]["humidity"]
@wind = weather.parsed_response["wind"]["speed"]
@description = weather.parsed_response["weather"][0]["description"]
@image = @@route_image
=end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_routes_controller.rb
class UserRoutesController < ApplicationController

  def create
    route = Route.where(route_id: params[:route]).first
    @user_route = UserRoute.create(user: current_user, route: route)
    redirect_to root_path
  end

  def destroy
    route = Route.find(params[:id])
    @user_route = UserRoute.where(user_id: current_user.id, route_id: route.id).first
    @user_route.destroy
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if current_user
      @user = current_user
      @user_routes = current_user.routes
    end
  end

  def post
    route = Route.where(name: params[:name]).first
    if route
      session[:route_id] = route.route_id
      redirect_to welcome_yourroute_path
    else
      redirect_to root_path(:id => 1)
    end
  end

  def yourroute
    @route = Route.build_route(session[:route_id])
    @weather = Weather.new(@route.lat, @route.lng)
  end

  def comments
    @route = Route.build_route(session[:route_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_routes_helper.rb
module UserRoutesHelper
end

app/views/layouts/_nav.html.erb
<!-- <div class="navbar navbar-default navbar-static-top">
  <div class="container">
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <h1><center> <%= link_to "Hit The Proj?", root_path, id: "thenav" %></center></h1>
        <ul class="nav navbar-right col-md-4">
        </ul>
      </div>
  </div>
</div> -->
<div class="navbar navbar-default navbar-static-top">
  <div class="row">
    <div class="col-xs-4" style="margin-top: 29px;">
      <% if current_user %>
        <span class="glyphicon glyphicon-user"></span>
        <%= current_user.email %>
      <% end %>
    </div>
    <div class="col-xs-4 text-center">
      <h1> <%= link_to "Hit The Proj?", root_path, id: "thenav" %></h1>
    </div>
    <div class="col-xs-4 text-right" style="margin-top: 29px;">
        <% if current_user %>
          <%= link_to("logout", destroy_user_session_path, class: "btn btn-danger", method: :delete) %>
        <% else %>
          <%= link_to("login", new_user_session_path, class: "btn btn-primary") %>
          <%= link_to("sign up", new_user_registration_path, class: "btn btn-success") %>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RouteFinder</title>
    <%= Gon::Base.render_data %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id='home-body'>
    <%= render 'layouts/nav' %>
    <div class="container">
    <%= yield %>
  </body>
</html>

app/views/welcome/_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Favorites</th>
    </tr>
  </thead>
  <tbody>
    <% @user_routes.each do |route| %>
      <tr>
        <td><%= route.name %></td>
        <td class="deleteButton"><%= link_to "Delete this route", user_route_path(route),
                      method: :delete,
                      class: "btn btn-xs btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<button type="button" class="btn btn-danger" name="button" onclick="toggleStyle()">Delete a route</button>

app/views/welcome/comments.html.erb
<body onload="changeImage('<%= @route.image %>')">
  <div class="heroine-image" id="bgImage">
    <div class="hero-text">
      <div class="container">
        <div class="row justify-content-end">
          <div class="col-sm-4 col-sm-offset-2">
            <form>
              <div class="form-group routeInfo">
                <div class="well well-lg each_box" id="testId">
                  <h2 style="color:black;">Most Recent Comment</h2>
                    <%= @route.new_comment %>
                </div>
              </div>
            </form>
          </div>
          <div class="col-sm-4">
            <form>
              <div class="form-group routeInfo">
                <div class="well well-lg each_box">
                  <h2 style="color:black;">Oldest Comment</h2>
                    <%= @route.old_comment %>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/welcome/index.html.erb
<div class="row">
<% if @user && @user.routes.count > 0 %>
  <div class="col-sm-10">
<% else %>
  <div class="col-sm-12">
<% end %>
    <div class="hero-image">
      <div class="hero-text">
        <h1 style="font-size:30px">What route would you like to climb today?</h1>
        <%= form_tag(welcome_index_path) do %>
        <% if params[:id] %>
          <p style="color:black;"><%= text_field_tag :name, value = nil, id: "searchInput", placeholder: "We couldn't find that route. Please try again!" %></p>
          <%= submit_tag 'Search', class: 'btn btn-primary', id: "searchButton" %>
        <% else %>
          <p style="color:black;"><%= text_field_tag :name, value = nil, id: "searchInput", placeholder:"Route Name" %></p>
          <%= submit_tag 'Search', class: 'btn btn-primary', id: "searchButton" %>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% if @user && @user.routes.count > 0 %>
  <div class="col-sm-2">
    <%= render 'list' %>
  </div>
<% end %>
</div>

<div>

</div>

app/views/welcome/yourroute.html.erb
<body onload="changeImage('<%= @route.image %>')">
  <div class="heroine-image" id="bgImage">
    <div class="hero-text">
      <div class="container">
        <div class="row justify-content-end">
          <div class="col-sm-4 col-sm-offset-2">
            <form>
              <div class="form-group routeInfo">
                <div class="well well-lg each_box" id="testId">
                  <h2 style="color:black;"><%= link_to "Your Route", welcome_comments_path, method: :get %> </h2>
                  <p><span style="color:wheat">Route Name:</span> <%= @route.name %></p>
                  <p><span style="color:wheat">Route Grade:</span> <%= @route.rating %></p>
                  <p><span style="color:wheat">Pitches:</span> <%= @route.pitch %></p>
                  <p><span style="color:wheat">Route Stars:</span> <%= @route.stars %></p>
                </div>
              </div>
            </form>
          </div>
          <div class="col-sm-4">
            <form>
              <div class="form-group routeInfo">
                <div class="well well-lg each_box">
                  <h2 style="color:black;">Weather</h2>
                  <h4><%= @weather.description %></h4>
                  <p><span style="color:wheat">Temperature:</span> <%= @weather.temp %></p>
                  <p><span style="color:wheat">Humidity:</span> <%= @weather.humidity %></p>
                  <p><span style="color:wheat">Wind:</span> <%= @weather.wind %></p>
                  <% if current_user.can_add_route?(@route.route_id) %>
                    <p><%= link_to "Add to my favorites", user_routes_path(user: current_user,
                                              route: @route.route_id),
                                              class: "btn btn-xs btn-success",
                                              method: :post %></p>
                  <% end %>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
<div id="map"></div>

<script>
  function initMap() {
      map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: gon.latt, lng: gon.lngg},
        zoom: 11,
      });
      var marker = new google.maps.Marker({
          position: {lat: gon.latt, lng: gon.lngg},
          map: map,
          title: 'Hello World!'
        });
      document.getElementById("map").style.height = "350px";
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key="
async defer></script>